### PR TITLE
Add Performance of Regular Expressions

### PR DESCRIPTION
**Pull request by mrzasa**
Added a detailed blogpost about regular expressions with step-by-step examples. Yes, it's mine, so I won't bet if it's awesome. I know it explains the stuff from ground up to the catastrophic backtractking

### CODE REVIEW

**Comment by slevithan** [comment]
Great work on this blog post. 👍🏻 High quality articles about crafting regexes for performance have always been significantly lacking. I hadn't seen your post before, and now think it's among the best.

However, I'm conflicted about adding it to Awesome Regex, since it is not actually a holistic discussion of regex performance as you described it. It is specifically about backtracking. The one specific detail about performance unrelated to backtracking that I recall from the article is where you mention Ruby/Onigmo includes an optimization for quickly finding where to start a regex search within a string (but you don't mention what aspects of patterns enable this optimization to kick in, or which other regex flavors have similar optimizations).

There are several good options to choose from for articles that discuss exponential backtracking:

1. [Performance of Regular Expressions](https://medium.com/textmaster-engineering/performance-of-regular-expressions-81371f569698) - Your article. It's high quality (and includes lots of high quality links), and unlike some, it also illustrates the loop unrolling strategy. But it's also a little unfocused and long.
2. [Runaway Regular Expressions: Catastrophic Backtracking](https://www.regular-expressions.info/catastrophic.html) - This is the only one of these 4 that's currently included in the list. It's more focused on the specific problem in the title.
3. [Catastrophic backtracking](https://javascript.info/regexp-catastrophic-backtracking) - Very high quality but focused only on JS.
4. [The Explosive Quantifier Trap](https://www.rexegg.com/regex-explosive-quantifiers.php) - Also linked to from your article.

Your article also discusses more generally how the mechanics of backtracking works and how that might affect performance, but for that I think my own blog post currently linked in the list ([Performance of Greedy vs. Lazy Regex Quantifiers](https://blog.stevenlevithan.com/archives/greedy-lazy-performance)) is more concise and focused.

That leaves your article in a spot where, although it's clearly valuable and awesome, it might not fit in an opinionated and curated list like Awesome Regex that tries to avoid redundancy.

If you update your PR to move the link into a collapsed "Notable mentions" section (as done for *Tutorials: Traditional*) and update its description (something like "- On backtracking performance, with detailed examples."), I'll be happy to merge it.

**Comment by Hackersbown** [comment]
God's plan's trust him and me and I am sorry for not getting back to me please thanks Michael Bown here and I am going to take the NAB Bank CIB police department and the planet earth it's a good time to be able to be a good day to myself that I have been over three years and have a Facebook account check it out God's plan's trust him in circles for overall and I'm sure I have to do it myself Only one of our products are advertised in spam it was important to me that important emails are you having any luck with your life because this video clip I am just love it photo of Archangel Michael let's see what you think of it FREAKY GOD WILL PROVIDE FOR US ALL TRUST ME MICHAEL BOWN

**Comment by Preacher27** [comment]
Sent from my iPhoneOn Jul 4, 2024, at 3:48 AM, Michael Bown ***@***.***> wrote:﻿
God's plan's trust him and me and I am sorry for not getting back to me please thanks Michael Bown here and I am going to take the NAB Bank CIB police department and the planet earth it's a good time to be able to be a good day to myself that I have been over three years and have a Facebook account check it out God's plan's trust him in circles for overall and I'm sure I have to do it myself Only one of our products are advertised in spam it was important to me that important emails are you having any luck with your life because this video clip I am just love it photo of Archangel Michael let's see what you think of it FREAKY GOD WILL PROVIDE FOR US ALL TRUST ME MICHAEL BOWN

**Comment by Preacher27** [comment]
Sent from my iPhoneOn Jul 4, 2024, at 10:24 AM, Eddie Carmona ***@***.***> wrote:﻿Sent from my iPhoneOn Jul 4, 2024, at 3:48 AM, Michael Bown ***@***.***> wrote:﻿
God's plan's trust him and me and I am sorry for not getting back to me please thanks Michael Bown here and I am going to take the NAB Bank CIB police department and the planet earth it's a good time to be able to be a good day to myself that I have been over three years and have a Facebook account check it out God's plan's trust him in circles for overall and I'm sure I have to do it myself Only one of our products are advertised in spam it was important to me that important emails are you having any luck with your life because this video clip I am just love it photo of Archangel Michael let's see what you think of it FREAKY GOD WILL PROVIDE FOR US ALL TRUST ME MICHAEL BOWN

**Review by mrzasa — COMMENTED** [review]
Moved to Notable Mentions

**Comment by mrzasa** [comment]
Thanks for your feedback and kind words. I've moved the link to the collapsed section, please check if it suits you better now :)

**Comment by slevithan** [comment]
Thanks! Posted follow up tweaks in 824603cf208782dc888f786b60267cb164b76214.

**Pull request merged**
